# Generated by Django 2.1 on 2018-09-06 06:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


# noinspection PyPep8,PyPep8
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('expiry', models.DateTimeField()),
            ],
            options={
                'db_table': 'access_token',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('language', models.CharField(choices=[('man', 'mandarin'), ('spa', 'spanish'), ('eng', 'english'), ('hin', 'hindi'), ('ara', 'arabic'), ('por', 'portuguese'), ('ben', 'bengali'), ('rus', 'russian'), ('jap', 'japanese'), ('pun', 'punjabi')], max_length=5)),
                ('currency', models.CharField(choices=[('USD', 'U.S.DOLLARS'), ('EUR', 'EUROS'), ('JPY', 'JAPANESE YEN'), ('GBP', 'GREAT BRITAIN POUND'), ('AUD', 'AUSTRALIAN DOLLARS'), ('CAD', 'CANADIAN DOLLARS'), ('CHF', 'SWISS FRANC'), ('CNY', 'CHINESE YUAN'), ('INR', 'INDIAN RUPEE')], max_length=3)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('geo_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_area.Company')),
            ],
            options={
                'db_table': 'service_area',
            },
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_area.Company'),
        ),
    ]
